[package]
name = "elden-cockring"
version = "0.1.0"
edition = "2021"

[dependencies]
buttplug = "5.1.7"
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "io-std", "process"] }
